name: GHA-PR-test

on:
  pull_request_target:
    branches:
      - master

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Use cancel redundant
        uses: technote-space/auto-cancel-redundant-job@v1.4.3

  job2:
    name: Job 2-${{ matrix.case }}
    needs: job1
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        case: [1, 2, 3]

    steps:
      - name: Use cancel redundant
        uses: technote-space/auto-cancel-redundant-job@v1.4.3

      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Run job
        run: ./myscript.sh
